name: Nightly Test Run

on:
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.0]  

    steps:   
       - name: Run specific tests (tests.GoogleFinanceTest)
         if: ${{ github.event.inputs.test_mode == 'tests.GoogleFinanceTest' }}
         run: |
           python -m unittest tests.GoogleFinanceTest

  

