name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Choose the test set to run'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.0]  

    steps:   
       - name: Run specific tests (tests.GoogleFinanceTest)
         if: ${{ github.event.inputs.test_mode == 'tests.GoogleFinanceTest' }}
         run: |
           python -m unittest tests.GoogleFinanceTest
